// <Douglas Edmonson Jr>. Copyright (C) 2014. MIT.
#ifndef HEADER_SRC_LIBINFO_H_INCLUDED
#define HEADER_SRC_LIBINFO_H_INCLUDED

#include <boost/preprocessor/stringize.hpp>

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "appinfo.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
#define LIBRARY_NAME               "CBOR++"
#define LIBRARY_CODENAME           "cbor++"
#define LIBRARY_COPYRIGHT_YEARS    "2014"
/* #undef LIBRARY_VERSION_MAJOR */
#define LIBRARY_VERSION_MINOR      1
/* #undef LIBRARY_VERSION_PATCH */
/* #undef LIBRARY_VERSION_TYPE */
#define LIBRARY_VERSION_STRING     "0.1.0"
#define LIBRARY_VENDOR_ID          "com.dedmonson"
#define LIBRARY_VENDOR_NAME        "Douglas Edmonson Jr"
#define LIBRARY_VENDOR_URL         "dedmonson.com"
#define LIBRARY_ID                 "com.dedmonson"

#ifndef LIBRARY_NAME
#   error "Please specify the application name in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_CODENAME
#   error "Please specify the application codename in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_COPYRIGHT_YEARS
#   error "Please specify the application copyright years (years during which this application was created, edited, or modified) in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VERSION_MAJOR
#   define LIBRARY_VERSOIN_MAJOR 0
#endif

#ifndef LIBRARY_VERSION_MINOR
#   define LIBRARY_VERSION_MINOR 0
#endif

#ifndef LIBRARY_VERSION_PATCH
#   define LIBRARY_VERSION_PATCH 0
#endif

#ifndef LIBRARY_VERSION_STRING
#   define LIBRARY_VERSION_STRING LIBRARY_VERSION_MAJOR "." LIBRARY_VERSION_MINOR "." LIBRARY_VERSION_PATCH
#endif

#ifndef LIBRARY_VENDOR_ID
#   error "Please specify the application vendor id in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VENDOR_NAME
#   error "Please specify the application vendor name in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VENDOR_URL
#   error "Please specify the application vendor URL in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_ID
#   define LIBRARY_ID LIBRARY_VENDOR_ID "." LIBRARY_CODENAME
#endif

#endif
